services:
    postgres:
        image: postgres:15 # Utilisation de l'image officielle de PostgreSQL
        container_name: postgres_db # Nom du conteneur pour PostgreSQL
        ports:
            - "5432:5432" # Exposition du port 5432 pour la connexion à la base de données
        environment:
            POSTGRES_USER: postgres # Nom d'utilisateur de PostgreSQL
            POSTGRES_PASSWORD: postgres # Mot de passe de PostgreSQL
            POSTGRES_DB: postgres # Nom de la base de données par défaut
        volumes:
            - db_data:/var/lib/postgresql/data # Volume persistant pour les données PostgreSQL
            - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    api:
        build:
            context: .
            dockerfile: DockerFile
        container_name: api_container
        ports:
            - 3000:3000
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            POSTGRESS_HOST: "postgres_db"
            POSTGRESS_PORT: 5432
            POSTGRESS_USER: "postgres"
            POSTGRESS_PASSWORD: "postgres"
        depends_on:
        - postgres

volumes:
    db_data: # Volume persistant pour les données de la base de données PostgreSQL
